[env:esp32dev]
; familia del chip; espressif32 trae el soporte del ESP32
platform = espressif32 @ 7.0.1
; la placa específica, un ESP32 genérico
board = esp32dev
; usar el framework Arduino (hace que #include <Arduino.h> funcione)
framework = arduino
; velocidad del monitor serial, coincide con Serial.begin(115200)
monitor_speed = 115200
