name: build
on:
  push:
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      - run: pip install platformio
      - run: pio run
      - uses: sigstore/cosign-installer@ba7bc0a3fef59531c69a25acd34668d6d3fe6f22 # v4.1.0
      - run: cosign sign-blob .pio/build/esp32dev/firmware.bin --bundle firmware.bundle --yes 
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: firmware
          path: .pio/build/esp32dev/firmware.bin
    
    
